### PR TITLE
Fix first empty comment line and missing last empty line

### LINKED ISSUE #6: Do not insert first empty comment line
Hi, I'm using this extension with setting `copyrightInserter.useLineComment` set as true.
I don't like that it add a first empty line at the top of the copyright, e.g.:
```
//
// Copyright (c) 2020 Sorint.lab S.p.A.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
...
```
But I'd like it to be:
```
// Copyright (c) 2020 Sorint.lab S.p.A.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
...
```

Would you mind if I open a PR for this?
Or would be this an option in settings maybe?

Here the patch:
```
diff --git a/src/copyrightinserter.ts b/src/copyrightinserter.ts
index eb21060..98e5d82 100644
--- a/src/copyrightinserter.ts
+++ b/src/copyrightinserter.ts
@@ -255,7 +255,7 @@ along with this program.  If not, see <https://www.gnu.org/licenses/>.`]
             }
         } else if (c!.lineComment) {
             const prefix = c!.lineComment + " ";
-            header = this.formatString(header, prefix, prefix, "");
+            header = this.formatString(header, "", prefix, "");
         } else {
             header = this.formatString(header, "", "", "");
         }
```

Thanks in advance

### LINKED ISSUE #7: Insert last empty line
I'm using this extension with setting `copyrightInserter.useLineComment` set as `false`, this time :) .
I don't like that it doesn't add last empty line at the bottom of the copyright, e.g.:
```
...
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package marshal

...
```
But I'd like it to be:
```
...
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package marshal

...
```

Would you mind if I open a PR for this?
Or would be this an option in settings maybe?

Here the patch:
```
diff --git a/src/copyrightinserter.ts b/src/copyrightinserter.ts
index eb21060..fe72347 100644
--- a/src/copyrightinserter.ts
+++ b/src/copyrightinserter.ts
@@ -240,7 +240,11 @@ along with this program.  If not, see <https://www.gnu.org/licenses/>.`]
             const new_line = prefix + line;
             result += new_line.trimRight() + "\n";
         }
-        return result += last_line + "\n";
+        if (last_line !== "") {
+            result += last_line + "\n";
+        }
+
+        return result += "\n";
     }
 
     private formatHeader(template: (holder: string, year: string) => string, data: CopyrightData, language: vscode.LanguageConfiguration, useLineComment: boolean): string {

```

Thanks in advance

### PR DESCRIPTION
**Pull request by cirelli94**
Fix #6 
Fix #7

### CODE REVIEW

**Comment by minherz** [comment]
I understand the problem that you are trying to solve. However, given you are a first person to complain about it, removing the lines is a too radical solution. Mind that someone else who like the empty lines before and after comment may open another issue like you did and to request having this one line margin between the copyright comment and the content back.
I am OK to make an _empty_ line margin configurable. It would be great having a configuration that enables/disables adding an empty line before and after the copyright comment.
Let me know if you would be interested to implement it. Otherwise, I will do it based on my availability.

**Comment by minherz** [comment]
@cirelli94 would you be so kind to provide feedback to [my comment ](https://github.com/minherz/copyright-inserter/pull/8#issuecomment-832068502)?

**Comment by cirelli94** [comment]
@minherz busy week!
Yes, I'd like to implement this.
How would you name this configurations and which default values would you like them to be?

**Comment by minherz** [comment]
Something like `copyrightInserter.addEmptyLineMargin`, type: "boolean", default: true,

**Comment by cirelli94** [comment]
Two distinct values, `addTopEmptyLineMargin` and `addBottomEmptyLineMargin` ?

**Comment by minherz** [comment]
I prefer to keep one config value for this. Mind that the empty line above is part of the comment and is there only to facilitate cases when there is a code before the comment (e.g. `#!/bin/bash` in shell scripts).
Too many config values create ambiguous configurations and aren't useful. Since you are the first person who raised the request to remove the empty lines, I prefer not to overcomplicate the configuration.
Thank you

**Comment by cirelli94** [comment]
:thinking: the fact is that today is has an inconsistent behaviour if it's using `useLineComment` or not.
Because with `useLineComment` it will add an empty comment line `\\` at the top and an empty line at the bottom.
While with `useLineComment` false it will use the first line for starting and the last for ending the multiline comment,, and so without leaving an emtpy line at the bottom!

>I prefer to keep one config value for this. Mind that the empty line above is part of the comment and is there only to facilitate cases when there is a code before the comment (e.g. #!/bin/bash in shell scripts).

Is this autodetect and the copyright inserted after that?

**Comment by minherz** [comment]
I am not sure what you mean by "autodetect" but this is what code does for _known_ cases. Than you for noticing the differences between multiline and single line comment presentation. It should be fixed. But it does not change the reasoning to keep number of config variables minimal. The main point regarding "extra" lines is that the sense of beauty and style is different for different people. you are the first who pointed to the extra lines as a problem, hence it isn't a real problem. Or, at least, not a problem that requires extra customization.

**Comment by minherz** [comment]
Closed since no work is done for 3 months.

**Pull request closed without merging**
